name: ImGui.Forms Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2

    # Setup the build
    - name: Wait for other release builds
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.303

    - name: Build ImGui.Forms
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --output nuget

    - name: Publish ImGui.Forms
      run: |
        foreach($file in (Get-ChildItem "nuget" -Recurse -Include *.nupkg)) {
          dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
